# Graphene with magnetic impurities

In [1]:
import kwant
import tinyarray
import numpy as np
import matplotlib.pyplot as plt
from itertools import product

In [5]:
#====================================================================#
#                    Lattice definitions                           #
#====================================================================#
## Matrix Definitions:
sigma_0 = tinyarray.array([[1,0],[0,1]])
sigma_x = tinyarray.array([[0,1],[1,0]])
sigma_y = tinyarray.array([[0,-1j],[1j,0]])
sigma_z = tinyarray.array([[1,0],[0,-1]])


## Graphene lattice Definition:
sin_30 = 1/2
cos_30 = np.sqrt(3)/2

graphene = kwant.lattice.general([(1, 0), (sin_30, cos_30)], # primitive vectors
                                 [(0, 0), (0, 1 / np.sqrt(3))],        # coord. of basis atoms
                                 norbs = 4,                            # number of orbitals per site (spin)
                                 name='Graphene'                       # name of identification
                                )
## Split in sublattices:
A, B = graphene.sublattices

## Adatom lattice definition:
hydrogen = kwant.lattice.general([(1, 0), (sin_30, cos_30)],    # primitive vectors
                                 [(0, 0), (0, 1 / np.sqrt(3))], # coord. of basis atoms
                                 norbs = 4,
                                 name='H')

## Split in sublattices
HA, HB = hydrogen.sublattices

## Physical constants
g_Lande = 2
Magneton_Bohr = 5.788e-5 # eV/T

In [4]:
np.kron(sigma_z, sigma_0)

array([[ 1,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [5]:
np.kron(sigma_x, sigma_0)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [9]:
np.kron(sigma_y, sigma_0).imag

array([[ 0.,  0., -1., -0.],
       [ 0.,  0., -0., -1.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

## Tests for generalization

In [11]:
type(tinyarray.array(np.kron(sigma_x, np.identity(1))))

tinyarray.ndarray_float

In [16]:
s_x = np.array([[ 0,  1],[ 1, 0]])
s_y = np.array([[ 0,-1j],[1j, 0]])
s_z = np.array([[ 1,  0],[ 0,-1]])

H_J_matrix = tinyarray.array(np.kron(s_x, s_x) + np.kron(s_y, s_y) + np.kron(s_z, s_z))

In [18]:
H_J_matrix

array([[(1+0j), 0j, 0j, 0j],
       [0j, (-1+0j), (2+0j), 0j],
       [0j, (2+0j), (-1+0j), 0j],
       [0j, 0j, 0j, (1+0j)]])

In [20]:
tinyarray.array(5 * s_x) 

array([[0, 5],
       [5, 0]])